In [36]:
import numpy as np

In [4]:
l=[3,4,57,83,567]

In [8]:
m=np.array(l)
print(type(m))

<class 'numpy.ndarray'>


In [9]:
m1=np.array(range(0,100))
print(m1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [11]:
np.random.random(5)

array([0.60270879, 0.76816782, 0.35635058, 0.41426315, 0.57603985])

In [12]:
m.ndim

1

In [15]:
m.shape

(5,)

In [16]:
m.dtype

dtype('int64')

In [17]:
m.itemsize

8

In [18]:
m.size

5

In [56]:
print(list(m.flat))

[np.int64(3), np.int64(4), np.int64(144), np.int64(144), np.int64(144)]


In [20]:
m

array([  3,   4,  57,  83, 567])

In [23]:
print(m[2])

57


In [24]:
m[2:5]=144

In [28]:
print(m)

m+5*10

[  3   4 144 144 144]


array([ 53,  54, 194, 194, 194])

In [30]:
print(m[m<100])

print(m[m>100])

[3 4]
[144 144 144]


In [33]:
print(np.max(m))
np.min(m)

144


np.int64(3)

In [34]:
l=[[1,2,3],[4,5,6],[7,8,9]]

In [37]:
c=np.array(l)

In [38]:
c.ndim #dimension find

2

In [39]:
c.shape #no of row and col

(3, 3)

In [44]:
a1=np.random.randint(1,100,(4,4))
print(a1)

[[62 25 44 63]
 [73  2 96 19]
 [79 90 40 54]
 [88 46 66  9]]


In [46]:
a1[2,2]

np.int32(40)

In [48]:
a1[2:,3]

array([54,  9], dtype=int32)

In [50]:
a1[2:,1:] #slicing

array([[90, 40, 54],
       [46, 66,  9]], dtype=int32)

In [51]:
a1.T # transpose of matric array

array([[62, 73, 79, 88],
       [25,  2, 90, 46],
       [44, 96, 40, 66],
       [63, 19, 54,  9]], dtype=int32)

In [53]:
a1.flatten() # chanege the single dimension array

array([62, 25, 44, 63, 73,  2, 96, 19, 79, 90, 40, 54, 88, 46, 66,  9],
      dtype=int32)

In [54]:
a1.reshape(8,2)# changing the row and col

array([[62, 25],
       [44, 63],
       [73,  2],
       [96, 19],
       [79, 90],
       [40, 54],
       [88, 46],
       [66,  9]], dtype=int32)